export const CONSTANTS = {
    WINDOW_WIDTH: 1089,
    WINDOW_HEIGHT: 792,
    TERRAIN_TILE_SIZE: 99,
    PLAYER_TILE_SIZE: 32*3,
    PLATFORM: 'platform',
    PLATFORM_TEXTURE_PATH: 'tile.png',
    BALL: 'ball',
    BALL_TEXTURE_PATH: 'ball.png',
    WINTILE: 'winTile',
    WINTILE_TEXTURE_PATH: 'winTile.png',
    PLAYER: 'player',
    PLAYER_OUTLINE: 'playerOutline',
    PLAYER_TEXTURE_PATH: 'Players/No Outlines/players blue x3.png',
    PLAYER_OUTLINE_TEXTURE_PATH: 'Players/players blue x3.png',
    PLAYER_IDLE: 'playerIdle',
    PLAYER_RUN: 'playerRun',
    PLAYER_DEATH: 'playerDeath',
    PLAYER_IDLE_OUTLINE: 'playerIdleOutline',
    PLAYER_RUN_OUTLINE: 'playerRunOutline',
    PLAYER_DEATH_OUTLINE: 'playerDeathOutline',
}